// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoulFoodAiBack.Data;

#nullable disable

namespace SoulFoodAiBack.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260401202858_AddCamposIngredient")]
    partial class AddCamposIngredient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoulFoodAiBack.Models.FoodPlan", b =>
                {
                    b.Property<int>("IdFoodPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFoodPlan"));

                    b.Property<double>("CarbPercent")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("FatPercent")
                        .HasColumnType("float");

                    b.Property<string>("FoodPlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("ProteinPercent")
                        .HasColumnType("float");

                    b.Property<double>("VegetableminPercent")
                        .HasColumnType("float");

                    b.HasKey("IdFoodPlan");

                    b.ToTable("FoodPlans");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.FoodPlanMeal", b =>
                {
                    b.Property<int>("IdFoodPlanMeal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFoodPlanMeal"));

                    b.Property<double>("CarbPercent")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("FatPercent")
                        .HasColumnType("float");

                    b.Property<int>("IdFoodPlan")
                        .HasColumnType("int");

                    b.Property<int>("IdMeal")
                        .HasColumnType("int");

                    b.Property<double>("ProteinPercent")
                        .HasColumnType("float");

                    b.Property<double>("VegetableminPercent")
                        .HasColumnType("float");

                    b.HasKey("IdFoodPlanMeal");

                    b.HasIndex("IdFoodPlan");

                    b.HasIndex("IdMeal");

                    b.ToTable("FoodPlanMeals");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.Goal", b =>
                {
                    b.Property<int>("IdGoal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGoal"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdGoal");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.Ingredient", b =>
                {
                    b.Property<int>("IdIngredient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIngredient"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Carbs")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Fat")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Kcal")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OpenFoodFactsId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdIngredient");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.Intolerance", b =>
                {
                    b.Property<int>("IdIntolerance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIntolerance"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IntoleranceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdIntolerance");

                    b.ToTable("Intolerances");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.Meal", b =>
                {
                    b.Property<int>("IdMeal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMeal"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdMeal");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.Recipe", b =>
                {
                    b.Property<int>("IdRecipe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecipe"));

                    b.Property<double>("Carbs")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Fat")
                        .HasColumnType("float");

                    b.Property<string>("IngredientsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TotalKcal")
                        .HasColumnType("int");

                    b.HasKey("IdRecipe");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.UserData", b =>
                {
                    b.Property<int>("IdUserData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserData"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<int>("IdFoodPlan")
                        .HasColumnType("int");

                    b.Property<int>("IdGoal")
                        .HasColumnType("int");

                    b.Property<int>("IdIntolerance")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("MealsPerDay")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("IdUserData");

                    b.HasIndex("IdFoodPlan");

                    b.HasIndex("IdGoal");

                    b.HasIndex("IdIntolerance");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("UserDatas");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.UserDiary", b =>
                {
                    b.Property<int>("IdUserDiary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserDiary"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DietAdherence")
                        .HasColumnType("int");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("int");

                    b.Property<int>("HungerLevel")
                        .HasColumnType("int");

                    b.Property<int>("IdUserFoodPlan")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SleepQuality")
                        .HasColumnType("int");

                    b.HasKey("IdUserDiary");

                    b.HasIndex("IdUserFoodPlan");

                    b.ToTable("UserDiaries");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.UserFoodPlanDaily", b =>
                {
                    b.Property<int>("IdFoodPlanMeal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFoodPlanMeal"));

                    b.Property<double>("CarbPercent")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("FatPercent")
                        .HasColumnType("float");

                    b.Property<int>("IdFoodPlan")
                        .HasColumnType("int");

                    b.Property<int>("IdMeal")
                        .HasColumnType("int");

                    b.Property<double>("ProteinPercent")
                        .HasColumnType("float");

                    b.Property<int?>("RecipeIdRecipe")
                        .HasColumnType("int");

                    b.Property<int?>("UserFoodPlanWeekIdUserFoodPlan")
                        .HasColumnType("int");

                    b.Property<double>("VegetablePercent")
                        .HasColumnType("float");

                    b.HasKey("IdFoodPlanMeal");

                    b.HasIndex("IdFoodPlan");

                    b.HasIndex("IdMeal");

                    b.HasIndex("RecipeIdRecipe");

                    b.HasIndex("UserFoodPlanWeekIdUserFoodPlan");

                    b.ToTable("UserFoodPlansDaily");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.UserFoodPlanWeek", b =>
                {
                    b.Property<int>("IdUserFoodPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserFoodPlan"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFoodPlan")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalDailyKcal")
                        .HasColumnType("int");

                    b.HasKey("IdUserFoodPlan");

                    b.HasIndex("IdFoodPlan");

                    b.HasIndex("IdUser");

                    b.ToTable("UserFoodPlansWeek");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.UserIngredient", b =>
                {
                    b.Property<int>("IdUserIngredient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserIngredient"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdIngredient")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("IdUserIngredient");

                    b.HasIndex("IdIngredient");

                    b.HasIndex("IdUser");

                    b.ToTable("UserIngredients");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.FoodPlanMeal", b =>
                {
                    b.HasOne("SoulFoodAiBack.Models.FoodPlan", "FoodPlan")
                        .WithMany("FoodPlanMeals")
                        .HasForeignKey("IdFoodPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulFoodAiBack.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("IdMeal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodPlan");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.UserData", b =>
                {
                    b.HasOne("SoulFoodAiBack.Models.FoodPlan", "FoodPlan")
                        .WithMany()
                        .HasForeignKey("IdFoodPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulFoodAiBack.Models.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("IdGoal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulFoodAiBack.Models.Intolerance", "Intolerance")
                        .WithMany()
                        .HasForeignKey("IdIntolerance")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulFoodAiBack.Models.User", "User")
                        .WithOne("UserData")
                        .HasForeignKey("SoulFoodAiBack.Models.UserData", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodPlan");

                    b.Navigation("Goal");

                    b.Navigation("Intolerance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.UserDiary", b =>
                {
                    b.HasOne("SoulFoodAiBack.Models.UserFoodPlanWeek", "UserFoodPlan")
                        .WithMany()
                        .HasForeignKey("IdUserFoodPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserFoodPlan");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.UserFoodPlanDaily", b =>
                {
                    b.HasOne("SoulFoodAiBack.Models.FoodPlan", "FoodPlan")
                        .WithMany()
                        .HasForeignKey("IdFoodPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulFoodAiBack.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("IdMeal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulFoodAiBack.Models.Recipe", null)
                        .WithMany("UserFoodPlanMeals")
                        .HasForeignKey("RecipeIdRecipe");

                    b.HasOne("SoulFoodAiBack.Models.UserFoodPlanWeek", null)
                        .WithMany("UserFoodPlanMeals")
                        .HasForeignKey("UserFoodPlanWeekIdUserFoodPlan");

                    b.Navigation("FoodPlan");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.UserFoodPlanWeek", b =>
                {
                    b.HasOne("SoulFoodAiBack.Models.FoodPlan", "FoodPlan")
                        .WithMany()
                        .HasForeignKey("IdFoodPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulFoodAiBack.Models.User", "User")
                        .WithMany("UserFoodPlans")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.UserIngredient", b =>
                {
                    b.HasOne("SoulFoodAiBack.Models.Ingredient", "Ingredient")
                        .WithMany("UserIngredients")
                        .HasForeignKey("IdIngredient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulFoodAiBack.Models.User", "User")
                        .WithMany("UserIngredients")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.FoodPlan", b =>
                {
                    b.Navigation("FoodPlanMeals");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.Ingredient", b =>
                {
                    b.Navigation("UserIngredients");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.Recipe", b =>
                {
                    b.Navigation("UserFoodPlanMeals");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.User", b =>
                {
                    b.Navigation("UserData");

                    b.Navigation("UserFoodPlans");

                    b.Navigation("UserIngredients");
                });

            modelBuilder.Entity("SoulFoodAiBack.Models.UserFoodPlanWeek", b =>
                {
                    b.Navigation("UserFoodPlanMeals");
                });
#pragma warning restore 612, 618
        }
    }
}
