
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --configuration=production

FROM nginx:alpine AS runtime
COPY --from=build /app/dist/soul-food-ai-front/browser /usr/share/nginx/html
EXPOSE 80