sonar.projectKey=soul-food-ai-front
sonar.projectName=SoulFood AI Frontend

sonar.host.url=http://localhost:9000

sonar.sources=src/app
sonar.tests=src/app
sonar.test.inclusions=**/*.spec.ts

sonar.typescript.tsconfigPath=tsconfig.app.json

sonar.javascript.lcov.reportPaths=coverage/lcov.info, coverage/**/lcov.info

sonar.exclusions=**/*.html, **/*.css, **/*.scss, **/*.component.ts, **/*.module.ts, **/package-lock.json, **/node_modules/**