version: '3.8'

services:
  basedatos:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "PasswordTFG2026!!!"
    ports:
      - "1433:1433"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./src/Back/SoulFoodAiBack/SoulFoodAiBack
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=basedatos;Database=SoulFoodAI;User Id=sa;Password=PasswordTFG2026!!!;TrustServerCertificate=True;
    depends_on:
      - basedatos

  frontend:
    build:
      context: ./src/Front/soul-food-ai-front
    ports:
      - "4200:80"
    depends_on:
      - backend